name: Deploy via FTPS to cyber_Folks

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: 20
  BUILD_DIR: build   # Vite build trafia do dist/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy to FTP (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.FTP_PORT || 21 }}
          local-dir: ${{ env.BUILD_DIR }}/
          server-dir: public_html/
          exclude: |
            **/.git*
            **/node_modules/**
            **/.github/**
